version: '3.4'

services:
  dockervstest:
    image: ${DOCKER_REGISTRY}dockervstest
    build:
      context: .\DockerVSTest
      dockerfile: Dockerfile
      proxy:
        remoteurl: http://10.230.12.111:5000